version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: du+3s9dnU
    networks:
      - wordpress

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: du+3s9dnU
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge